content:
  - name: blog
    label: Blog
    path: content/blog
    view: 
      fields: [ title, date ] 
    type: collection
    fields: 
      - { name: title, label: Title, type: string }
      - { name: draft, label: Draft, type: boolean, default: true }
      - { name: date, label: Date, type: date }
      - { name: body, label: Body, type: rich-text }
media:
  input: public/img
  output: /public/img